### ISSUE TITLE
PAGES

### ISSUE THREAD

**Issue by scargill** [andrei-tatar/node-red-contrib-ui#18] opened 2015-12-10 07:28 UTC
Probably not an issue but I cannot see how to split stuff up into pages in node-red-contrib-ui - yet clearly the facility is there? Can you enlighten?

**Comment by andrei-tatar** [comment] 2015-12-10 07:37
Almost all nodes have a Tab property that you can configure. It defaults to Home but you can add a new one.

![image](https://cloud.githubusercontent.com/assets/6473183/11709626/97423a4e-9f21-11e5-858e-d332c2056bcd.png)

**Comment by scargill** [comment] 2015-12-10 08:05
Ah, THAT’s better – that wasn’t clear to me – right I’ve split stuff up into tabs. Very good.

 

Question – as you know, Nod-Red Admin can be password protected. I’ve just realised that of course this is not – a tad dangerous… any chance of implementing some kind of (optional?) username and pass… just so I feel a little more comfortable using this outside of the house?  VPNs are a pain.

 

Pete.

**Comment by andrei-tatar** [comment] 2015-12-10 12:22
You can use the default httpAdminAuth and it should protect the /ui path. The problem is that the socket.io endpoint is still available.
However, I only expose to the internet the /ui path (under a different path) and also secure it using apache.

**Comment by scargill** [comment] 2015-12-10 12:26
But Julian just got done saying that is now deprecated.

 

:(

**Comment by andrei-tatar** [comment] 2015-12-10 12:32
Oh, I wasn't aware of that.
Is node-red going to support any other kind of auth?
The point is, node-red-contrib-ui won't have it's own auth mechanism. You should rely on some other way of securing the endpoints.

**Comment by scargill** [comment] 2015-12-10 19:32
A request. The number field is great with the left and right arrows – but imagine it controlling heating – you might have 4 of them – on time 1, off time 1, on time 2, off time 2…  moving up and down would adjust the time by 30 minutes for example… right now the display would be meaningless.

 

So would it be possible to have a version of that node where the display part is handle separately. In other words operation would be the same – you could have 0-47 – but the display could then be injected on change to show 12:30, 13:00 etc….. ie any old text..

 

Is that possible?

 

Pete.

**Comment by andrei-tatar** [comment] 2015-12-11 06:53
You can actually do that right now but I also added sprintf.js library to format fields easier.
Here is what you need:
![image](https://cloud.githubusercontent.com/assets/6473183/11737685/7cdb2864-9fe4-11e5-8d7d-eb1b48563241.png)

The template:
```{{'%02d'|sprintf:value/2}}:{{'%02d'|sprintf:value%2*30}}```

And the result:
![image](https://cloud.githubusercontent.com/assets/6473183/11737710/a4c5ffa2-9fe4-11e5-820c-50ccae5df787.png)

**Comment by andrei-tatar** [comment] 2015-12-11 06:56
I'll close this issue. There also is a "node-red-contrib-ui" google group where you can post if you have questions.

**Closed by andrei-tatar** 2015-12-11 06:56 UTC

**Comment by scargill** [comment] 2015-12-11 07:23
If I leave the template alone- the up down works (obviously) if I put in the code you’ve suggested – nothing appears (not even the up down arrows).

**Comment by scargill** [comment] 2015-12-11 07:26
Ignore comment – just realised I have to upgrade
