### ISSUE TITLE
Vertical Align

### ISSUE THREAD

**Issue by scargill** [andrei-tatar/node-red-contrib-ui#27] opened 2015-12-12 08:50 UTC
I have tried everything I can think of to get those little icons to align vertically with text. I've even managed to get the paragraph the same height as other items - but I cannot align the text and imagery. Do you have any solution?

![screen2](https://cloud.githubusercontent.com/assets/1889411/11761180/d38ed874-a0af-11e5-892e-79bf273b5be8.png)

**Comment by Toshibass** [comment] 2015-12-12 14:28
Try adding this into your line   style=" position: relative; top:-5px;"  mod -5px to final position the icon like ....
<img height="32px" style=" position: relative; top:-5px;" ng-src="{{(msg.payload||1)==1 ? 'icons/On.png' : 'icons/Off.png'}}">

Toshi

**Comment by scargill** [comment] 2015-12-12 16:00
Stunning – works a treat.

**Comment by Toshibass** [comment] 2015-12-12 20:07
What I don't get is why the different type of nodes/widgets take up different height to the next widget for example see attached, or am I missing something fundamental regarding the layout, they should all have the same distance between them or they look junk.

![snip4](https://cloud.githubusercontent.com/assets/6310911/11763676/e41e594c-a10b-11e5-85c6-258a84a734d9.JPG)

**Comment by andrei-tatar** [comment] 2015-12-14 07:00
The problem was the "paragraph" node that was adding extra margin because was adding the template inside a <p> element that has a default top/bottom margin. I will add a fix. Also I recommend using this template without specifying sizes. They should center align just fine:

```
<div layout="row" layout-align="space-between center">
	<p flex>This is the topic</p>
	<ng-md-icon icon="brightness_1"></ng-md-icon>
</div>
```

**Comment by scargill** [comment] 2015-12-14 07:13
Excellent I will await notice that an update is ready – this is great work…

 

Pete.

**Comment by scargill** [comment] 2015-12-15 14:02
Guys – is it just me-   I just updated to the latest node-red-contrib-gui

 

And after fixing the paragraph entries – I did my normal 192.168.0.19:1880/ui

 

And…

 

The green bar is there – “pages” and “other” are in the menu – but my 3 pages are no-where to be seen – despite being active in Node-Red……  any ideas?

**Comment by andrei-tatar** [comment] 2015-12-15 14:11
Press F12 to open the developer console and hit refresh. Any errors?

**Comment by scargill** [comment] 2015-12-15 14:13
No just a couple of warnings about red itself

 

SVG's SMIL animations (<animate>, <set>, etc.) are deprecated and will be removed. Please use CSS animations or Web animations instead.

red.min.js:16 Node-RED: 0.12.2

 

I’m seeing nothing wrong but my heating controls have disappeared. Adding a new button and a new config doesn’t help so I don’t even know how to start to fix this….

**Comment by andrei-tatar** [comment] 2015-12-15 14:15
F12 and F5 when the "Node-RED ui" tab is active.

**Comment by scargill** [comment] 2015-12-15 14:15
Hang on doing a reboot – just to be sure…

**Comment by scargill** [comment] 2015-12-15 14:22
Panic over – a reboot fixed it but you might want to warn people about that – previous updates have not done that – I updated by “npm install node-red-config-ui”.

 

Works well, images are aligned in my LED indicator..

**Comment by andrei-tatar** [comment] 2015-12-15 14:23
Strange. Have you tried restarting node-red?

**Comment by scargill** [comment] 2015-12-15 14:32
All sorted…

 

Question  about alignment..

 

I just realised I can have TWO indicators on a line saving lots of space.

 

 

<div layout="row" layout-align="space-between center">

    <p flex>Active1</p>

    <ng-md-icon icon="wb_incandescent" ng-style="{fill:msg.payload=='1'?'green':'blue'}" size="32"></ng-md-icon>

    <p flex>Active2</p>

    <ng-md-icon icon="wb_incandescent" ng-style="{fill:msg.payload=='1'?'purple':'orange'}" size="32"></ng-md-icon>

</div>

 

But they are jammed together. I CAN put NB spaces before ACTIVE 2 but that only serves to narrow the RIGHT hand pair down – is there a way you can think of to leave a gap in the middle – reducing the width of BOTH items so they are even???

**Comment by scargill** [comment] 2015-12-15 14:34
Yes I had restarted node-red – to no avail – but rebooting the Pi sorted it… works well – looking forward to exploring possibilities for this new node… shame it can’t do includes etc or I could add a colour wheel now :)

 

Just for info… I just figured out how to get TWO evenly spaced LEDs onto a row..

 

This is just WAY better.. I’d feel better if I could actually make that spacer a fixed width but it works…

 

<div layout="row" layout-align="space-between center">

    <p flex>Active1</p>

    <ng-md-icon icon="wb_incandescent" ng-style="{fill:msg.payload=='1'?'green':'blue'}" size="32"></ng-md-icon>

    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

    <p flex>Active2</p>

    <ng-md-icon icon="wb_incandescent" ng-style="{fill:msg.payload=='1'?'purple':'orange'}" size="32"></ng-md-icon>

</div>

**Comment by andrei-tatar** [comment] 2015-12-15 14:39
There are lots of different ways of adding the empty space. Even a "<div style='width:10px'></div>" will do.
You should be able to also include scripts so you can add the color-wheel.

**Comment by scargill** [comment] 2015-12-15 14:47
I am just getting SO excited here.. more time – less sleep…..

 

I’m assuming “includes” are out….

Or is there somewhere else we could add includes (obviously with a chance of screwing everything up).

 

The reason I ask is..

 

http://www.jar2.net/projects/jquery-wheelcolorpicker

 

Where is says “try it here” – I’ve not tested this one on mobile – but if it works – I’d give my right arm to have that as an option….

**Comment by scargill** [comment] 2015-12-15 15:13
I might be missing something here.. are there any directives you could add to the code to make Android Chrome make these pages full screen - I just cannot find a way or removing the Android menu bar off the top - but I've seen it done...

**Comment by Hugobox** [comment] 2015-12-15 15:23
Hi!
I also updated and can't see the pages anymore, unfortunately a reboot
didn't solve it for me, the culprit seems to be ui_paragraph and ui_content:

* ------------------------------------------*
* Missing node modules:*
*  - node-red-contrib-ui: ui_paragraph, ui_content*

Hugo

**Comment by Hugobox** [comment] 2015-12-15 15:42
Allright, find-replace all ui_paragraph to ui_template + restart node-red
solved it for me

Hugo

**Comment by scargill** [comment] 2015-12-16 05:57
I am SO very nearly there now – got the Z-layering right – but I cannot get from your example TEXT output – to a variable

 

ng-mouseup="send({ payload: 'hmm' })"

 

See above – that works when I release the mouse from the colour control – it’s LOVELY – but… sending Hmm is no good.

 

The input box has ID FRED

 

I misguidedly thought I might be able to do..

 

ng-mouseup="send({ payload: $(‘fred’).val()  })"

 

But no.  Can you help with slightly better examples of getting data into and out of the template node – this has just so much potential.

 

Pete.

 

Here is my code altogether for the colour controller.. SPOT on but I need to get info into the control – and out of that input box.

 

<!DOCTYPE html>

<script type="text/javascript" src="jquery-1.7.1.min.js"></script>

<script type="text/javascript" src="jquery.wheelcolorpicker.js"></script>

<link type="text/css" rel="stylesheet" href="wheelcolorpicker.css" />

 

<span ng-mouseup="send({ payload: 'hmm' })" style="position: relative; z-index: 1;">

    

<input id="fred" style="position: relative; z-index: 1;" type="text" data-wheelcolorpicker="" data-wcp-layout="block">

 

</span>

 

The author gives great examples and I’m just too dumb to get that last bit right.

 

http://files.jar2.net/jquery/wheelcolorpicker/example-v2/example.html

**Comment by natcl** [comment] 2015-12-16 06:42
Try this: ng-mouseup="send({ msg: {payload: 'hmm'} })"

**Comment by andrei-tatar** [comment] 2015-12-16 06:58
It's more like this:
```html
<script type="text/javascript" src="http://files.jar2.net/jquery/wheelcolorpicker/example-v2/jquery.wheelcolorpicker.js"></script>
<link type="text/css" rel="stylesheet" href="http://files.jar2.net/jquery/wheelcolorpicker/example-v2/css/wheelcolorpicker.css" />

<span style="position: relative; z-index: 1;" ng-init="init()">
    <input id="{{$id}}" style="position: relative; z-index: 1;" type="text" data-wheelcolorpicker="" data-wcp-layout="block">
</span>

<script>
    scope.init = function() {
        var send = this.send;
        
        setTimeout(function(){
            var colorWheel = $('#'+this.$id);
            colorWheel.on('slidermove', function() {
        		send({payload: $(this).wheelColorPicker('getValue', 'rgb')});
        	});
        	
        	this.$on('$destroy', function() {
                colorWheel.wheelColorPicker('destroy');
            });
        }.bind(this), 0);
    };
</script>
```

But it doesn't keep it's state yet.

**Comment by andrei-tatar** [comment] 2015-12-16 07:01
Also, if you want to use more than one, you shouldn't re-include the same scripts/css.

**Comment by scargill** [comment] 2015-12-16 07:08
Erm that works already.. What I’m after is sending variables

**Comment by scargill** [comment] 2015-12-16 07:12
You’re my morning hero Andrei. I wanted on mouse up – but it occurs to me that we can add a DELAY node to slow down that horrendous rate of output… so now it’s a working piece of code-  just need to figure out to how to preset it…

**Comment by andrei-tatar** [comment] 2015-12-16 07:16
You could probably register for the slider release event (need to check the docs for that).

**Comment by scargill** [comment] 2015-12-16 07:16
Did as you suggest – replicated the code without the includes – sure enough – two of them work. When this is done I’ll adjust sizes etc to make it fill the width of your column properly.

 

All that remains now is to get a value set into it from the input  - this is on the edge of my JS understanding so if you Are able to figure out how to do it – you’re on my Christmas card list… 

 

Excellent

 

Pete.

**Comment by scargill** [comment] 2015-12-16 07:17
No I think that will do – one option in the delay event is to “limit the number of messages to X per second” – and that will sort that.

**Comment by scargill** [comment] 2015-12-16 07:31
I’ve updated the blog (tech.scargill.net) with progress so far and credit where credit is due… this is great…

**Comment by scargill** [comment] 2015-12-16 07:40
Sliderup works a treat

**Comment by scargill** [comment] 2015-12-16 08:27
By the look of it to set it you use 

 

        $(this).wheelColorPicker('setValue', string_value)

 

Just not sure WHERE to use it….

**Comment by andrei-tatar** [comment] 2015-12-16 08:33
This one should work

```html
<script type="text/javascript" src="http://files.jar2.net/jquery/wheelcolorpicker/example-v2/jquery.wheelcolorpicker.js"></script>
<link type="text/css" rel="stylesheet" href="http://files.jar2.net/jquery/wheelcolorpicker/example-v2/css/wheelcolorpicker.css" />

<span style="position: relative; z-index: 1;" ng-init="init()">
    <input id="{{$id}}" style="position: relative; z-index: 1;" type="text" data-wheelcolorpicker="" data-wcp-layout="block">
</span>

<script>
    scope.init = function() {
        var send = this.send;
        
        setTimeout(function(){
            var colorWheel = $('#'+this.$id);

            colorWheel.on('sliderup', function() {
        		send({payload: colorWheel.wheelColorPicker('getValue', 'rgb')});
        	});
        	
        	this.$watch('msg.payload', function (inColor) {
        	    if (!inColor) return;
        	    colorWheel.wheelColorPicker('setValue', inColor);
        	});
        	
        	this.$on('$destroy', function() {
                colorWheel.wheelColorPicker('destroy');
            });
        }.bind(this), 0);
    };
</script>
```

The problem is that it doesn't work the 1st time (because the wheelColorPicker is not yet loaded and jQuery loads all the scripts async). 
I could create a small hack that periodically checks if the colorWheel has been inited. It would also help if the colorWheel would fire an event when it has inited.

Either way, if you open 2 tabs, they should stay in sink after the components loaded.

**Comment by andrei-tatar** [comment] 2015-12-16 08:45
And here is the one with the hack the loads the set color (so if you hit refresh, or reload the page, the last color is loaded):

```html
<script type="text/javascript" src="http://files.jar2.net/jquery/wheelcolorpicker/example-v2/jquery.wheelcolorpicker.js"></script>
<link type="text/css" rel="stylesheet" href="http://files.jar2.net/jquery/wheelcolorpicker/example-v2/css/wheelcolorpicker.css" />

<span style="position: relative; z-index: 1;" ng-init="init()">
    <input id="{{$id}}" style="position: relative; z-index: 1;" type="text" data-wheelcolorpicker="" data-wcp-layout="block">
</span>

<script>
    scope.init = function() {
        var send = this.send;
        var timer;
        
        timer = setInterval(function() {
            var colorWheel = $('#'+this.$id);
            if (!colorWheel.wheelColorPicker) return;
            
            clearInterval(timer);
            
            colorWheel.on('sliderup', function() {
        		send({payload: colorWheel.wheelColorPicker('getValue', 'rgb')});
        	});

            var updateColor = function (inColor) {
        	    if (!inColor) return;
        	    colorWheel.wheelColorPicker('setValue', inColor);
        	};
            
            if (this.msg && this.msg.payload) updateColor(this.msg.payload);
            this.$watch('msg.payload', updateColor);
        	
        	this.$on('$destroy', function() {
                colorWheel.wheelColorPicker('destroy');
            });
        }.bind(this), 100);
    };
</script>
```

I don't really recommend using this, it looks really ugly. I think I'll make a real color picker node by the end of the week.

P.S. don't forget about the Christmas card list :))

**Comment by andrei-tatar** [comment] 2015-12-16 09:05
By the way, here's a simpler color picker that uses the default HTML5 color input (works nice on Android)

```html
<div layout="row" layout-align="space-between center">
    <p>Choose a color</p>
    <input type="color" 
           ng-model="msg.payload" 
           ng-change="send(msg)"
           style="border:0;padding:0">
</div>
```

**Comment by scargill** [comment] 2015-12-16 09:21
I was looking at that function and trying to figure it out as you could inject rgb(x,y,z) arbitrarily into the second box here..

 

http://files.jar2.net/jquery/wheelcolorpicker/example-v2/example.html

 

No, sorry your example does not work – the wheel never comes up – you just get the input box  - I’m sure it’s something trivial??? Just not trivial enough for me to see it.

**Comment by scargill** [comment] 2015-12-16 09:32
So the colour picker that I sent an email back to say it was not working – is – I think it coincided with our broadband dying.  It works a treat – and injecting an rgb value into it works….

 

The new simple one – well nice but not as nice….. does take up less room though…

 

I’ve not tried your LAST email yet..

**Comment by scargill** [comment] 2015-12-16 09:42
I’m talking rot – your first one works the FIRST time you inject something – but then if you manually move the controls – injecting does not move the colour a second time.

 

Your second one (the one you said you don’t recommend) is the same -  so put  an inject with text rgb(255,0,0) for example – start it up – press inject – SUPER moves the colour.. then alter the colour by hand in the UI – press the inject – it doesn’t to it a second time.

 

Also need a slight fix in that if you change the colour by hand/mouse – it makes an output. If you INJECT – it makes an output.

 

I suggest that the INJECT should make an output. But if we manually change the colour using the wheel – we need to inject that back in – to ensure any other colour wheels (ie one on the PC, one view on the mobile) stay in SYNC but clearly if THAT input had an outpout – you’d get a permanent loop.

 

But I think that feedback will have to be done internally – because you can’t just fasten an output back to the input of a node… it disappears around the back – or is removed altogether – hard to tell..

**Comment by scargill** [comment] 2015-12-16 09:44
Similar to my last email – we can have an inject input to preset this – but if you actually SET the control – somehow you need to feed that back so that any other device showing this screen updates…..??? This is nowhere near as pretty as the other wheel but the more the merrier as you could fit 2 of these on a line if you were short of space.

**Comment by andrei-tatar** [comment] 2015-12-16 12:28
There was a small template related bug. Fixed it in the last release. Let me know if it works now.

**Comment by scargill** [comment] 2015-12-16 14:31
Done that –still getting no-where with that inject only working once…

 

Another query – in your input example you use msg.payload – in the output example you use payload… ??

**Comment by andrei-tatar** [comment] 2015-12-16 14:44
This flow works fine for me:
```json
[{"id":"e7add40d.185228","type":"ui_tab","z":"4880859c.b77f7c","name":"Home","icon":"dashboard","order":"1"},{"id":"bbc91f4c.4436e","type":"ui_template","z":"4880859c.b77f7c","tab":"e7add40d.185228","name":"Big Color Picker","group":"","order":1,"format":"<script type=\"text/javascript\" src=\"http://files.jar2.net/jquery/wheelcolorpicker/example-v2/jquery.wheelcolorpicker.js\"></script>\n<link type=\"text/css\" rel=\"stylesheet\" href=\"http://files.jar2.net/jquery/wheelcolorpicker/example-v2/css/wheelcolorpicker.css\" />\n\n<span style=\"position: relative; z-index: 1;\" ng-init=\"init()\">\n    <input id=\"{{$id}}\" style=\"position: relative; z-index: 1;\" type=\"text\" data-wheelcolorpicker=\"\" data-wcp-layout=\"block\">\n</span>\n\n<script>\n    scope.init = function() {\n        var send = this.send;\n        var timer;\n\n        timer = setInterval(function() {\n            var colorWheel = $('#'+this.$id);\n            if (!colorWheel.wheelColorPicker) return; //not loaded yet, check again later\n            clearInterval(timer);\n\n            colorWheel.on('sliderup', function() {\n                send({payload: colorWheel.wheelColorPicker('getValue', 'rgb')});\n            });\n\n            var updateColor = function (inColor) {\n                if (!inColor) return;\n                colorWheel.wheelColorPicker('setValue', inColor);\n            };\n\n            if (this.msg && this.msg.payload) updateColor(this.msg.payload);\n            this.$watch('msg.payload', updateColor);\n\n            this.$on('$destroy', function() {\n                colorWheel.wheelColorPicker('destroy');\n            });\n        }.bind(this), 100);\n    };\n</script>","x":477,"y":142,"wires":[["64ea60ea.9b15a"]]},{"id":"dff5afc.f200a5","type":"ui_button","z":"4880859c.b77f7c","tab":"e7add40d.185228","name":"Red","payload":"rgb(255,0,0)","topic":"","group":"","order":"0","x":242,"y":76,"wires":[["bbc91f4c.4436e"]]},{"id":"fd4f88fa.02b078","type":"ui_button","z":"4880859c.b77f7c","tab":"e7add40d.185228","name":"Green","payload":"rgb(0,255,0)","topic":"","group":"","order":"0.1","x":246,"y":126,"wires":[["bbc91f4c.4436e"]]},{"id":"75cb01dd.8a35","type":"ui_button","z":"4880859c.b77f7c","tab":"e7add40d.185228","name":"Blue","payload":"rgb(0,0,255)","topic":"","group":"","order":"0.2","x":245,"y":181,"wires":[["bbc91f4c.4436e"]]},{"id":"64ea60ea.9b15a","type":"ui_toast","z":"4880859c.b77f7c","name":"","x":647,"y":144,"wires":[]}]
```

**Comment by andrei-tatar** [comment] 2015-12-16 15:01
I'll close this issue. This has gone way off topic.
Start a new topic on the group if this is still not working for you.

**Comment by scargill** [comment] 2015-12-16 15:02
Andrei I’m dying to try this – but for reasons beyond me I can’t paste that – well it pastes but the OK button doesn’t light up – I’m well familiar with pasting flows.. can you try again?

**Closed by andrei-tatar** 2015-12-16 15:01 UTC

**Comment by scargill** [comment] 2015-12-16 15:03
Ok over to google groups
